### ISSUE TITLE
Pattern matching for Option and Result

### ISSUE THREAD

**Issue by sporto** [AlexGalays/spacelift#11]
I saw this here https://github.com/Threestup/monads
Looks like a neat approach for pseudo pattern matching.

```
let result = Some("Sam")

let message = result.match({
    Some: res => `Hello ${res}`,
    None : () => 'Hello World',
})
```

It would be great to have this. In the example above I made the `None` case be a function, because you might have an expensive computation there or side effects.

**Comment by AlexGalays** [comment]
Hello,
Funny, It had it back then:  https://github.com/AlexGalays/option.ts/blob/master/option.ts#L50

I must have removed it because it wasn't very useful compared to `fold` and simulating pattern matching in a language that doesn't have them at all is a bit surprising.
I would be more inclined to wait for this proposal: https://github.com/tc39/proposal-pattern-matching and make spacelift nice to use with this new syntax.

**Comment by sporto** [comment]
Oh `fold`, I didn't even look at that. I was unfamiliar with this name for that. That works just fine.
